# ゴローデザイン AR リダイレクト設定
# 最終更新: 2026/07/18

[[redirects]]
  from   = "/ar/goro01"
  to     = "https://player.artivive.com/artworks/6a504ff7518e26df36783bde"
  status = 302
  force  = true

[[redirects]]
  from   = "/ar/meishi01"
  to     = "https://player.artivive.com/artworks/6a473ca0706c266602f31617"
  status = 302
  force  = true

[[redirects]]
  from   = "/ar/meishi02"
  to     = "https://player.artivive.com/artworks/69606537d0b32f03b0f74f54"
  status = 302
  force  = true

[[redirects]]
  from   = "/ar/moderu01"
  to     = "https://player.artivive.com/artworks/6a54e2b2518e26df368598e0"
  status = 302
  force  = true

[[redirects]]
  from   = "/ar/meishi03"
  to     = "https://player.artivive.com/artworks/6a548355518e26df3684846e"
  status = 302
  force  = true

[[redirects]]
  from   = "/ar/illuttration01"
  to     = "https://player.artivive.com/artworks/6a5467ae518e26df36843b0e"
  status = 302
  force  = true

[[redirects]]
  from   = "/ar/illuttration02"
  to     = "https://player.artivive.com/artworks/6a546861518e26df36843c93"
  status = 302
  force  = true

[[redirects]]
  from   = "/ar/illuttration03"
  to     = "https://player.artivive.com/artworks/6a546ae9518e26df36844530"
  status = 302
  force  = true

[[redirects]]
  from   = "/ar/illuttration04"
  to     = "https://player.artivive.com/artworks/6a5464bb518e26df36843436"
  status = 302
  force  = true

[[redirects]]
  from   = "/ar/illuttration05"
  to     = "https://player.artivive.com/artworks/69a64c9aee4d360782d1fc81"
  status = 302
  force  = true

[[redirects]]
  from   = "/ar/illuttration06"
  to     = "https://player.artivive.com/artworks/696aea9184b60d4576b02b2a"
  status = 302
  force  = true

[[redirects]]
  from   = "/ar/illuttration07"
  to     = "https://player.artivive.com/artworks/69637631dede66f382eecf4d"
  status = 302
  force  = true

[[redirects]]
  from   = "/ar/illuttration08"
  to     = "https://player.artivive.com/artworks/69d74d0285a156cf9d7543e6"
  status = 302
  force  = true

[[redirects]]
  from   = "/ar/illuttration09"
  to     = "https://player.artivive.com/artworks/69fc291085a156cf9de9ba50"
  status = 302
  force  = true

[[redirects]]
  from   = "/ar/illuttration10"
  to     = "https://player.artivive.com/artworks/6a22898385a156cf9d63b5c2"
  status = 302
  force  = true

[[redirects]]
  from   = "/ar/illuttration11"
  to     = "https://player.artivive.com/artworks/6a5466c5518e26df368438d1"
  status = 302
  force  = true

[[redirects]]
  from   = "/ar/shirasi01"
  to     = "https://player.artivive.com/artworks/697ac5f8929f569139ad64d3"
  status = 302
  force  = true

[[redirects]]
  from   = "/ar/syashin01"
  to     = "https://player.artivive.com/artworks/6a546520518e26df368434f9"
  status = 302
  force  = true

[[redirects]]
  from   = "/ar/shasinn02"
  to     = "https://player.artivive.com/artworks/6a544d16518e26df3683f812"
  status = 302
  force  = true

[[redirects]]
  from   = "/ar/chirasi04"
  to     = "https://player.artivive.com/artworks/6a546064518e26df3684293b"
  status = 302
  force  = true

[[redirects]]
  from   = "/ar/meishi04"
  to     = "https://player.artivive.com/artworks/68e70cf1ad2a00cc13035bd9"
  status = 302
  force  = true

[[redirects]]
  from   = "/ar/meishi05"
  to     = "https://player.artivive.com/artworks/69abf035ee4d360782e3bc1d"
  status = 302
  force  = true

[[redirects]]
  from   = "/ar/meishi16"
  to     = "https://player.artivive.com/artworks/6a58663b518e26df368f813a"
  status = 302
  force  = true

[[redirects]]
  from   = "/ar/meishi18"
  to     = "https://player.artivive.com/artworks/69b8ef82ee4d3607820add38"
  status = 302
  force  = true

